# Generated by Django 5.2.2 on 2025-12-30 20:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CardTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('trap_type', models.CharField(choices=[('MINUS_UP', 'Minus Up'), ('MINUS_DOWN', 'Minus Down'), ('MINUS_LEFT', 'Minus Left'), ('MINUS_RIGHT', 'Minus Right')], max_length=32)),
                ('value', models.IntegerField(default=1)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], default='active', max_length=16)),
                ('turn_player', models.IntegerField(default=1)),
                ('board_state', models.JSONField(default=list)),
                ('used_char_p1', models.JSONField(default=list)),
                ('used_char_p2', models.JSONField(default=list)),
                ('used_trap_p1', models.JSONField(default=list)),
                ('used_trap_p2', models.JSONField(default=list)),
                ('winner', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_p2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
                ('move_type', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.match')),
            ],
        ),
    ]
