# Generated by Django 5.2.2 on 2025-12-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcharacter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/characters/'),
        ),
        migrations.AddField(
            model_name='cardtrap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cards/traps/'),
        ),
    ]
