# Generated by Django 5.2.2 on 2025-12-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_matchqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hand_p1',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='hand_p2',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
