# Generated by Django 5.2.2 on 2026-01-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_match_hand_p1_match_hand_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hand_traps_p1',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='hand_traps_p2',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
