# Generated by Django 5.2.2 on 2026-01-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_match_turn_deadline_deck_deckcharacter_decktrap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcharacter',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL pública de la imagen (Cloudinary, CDN, etc). Se usa con prioridad.', null=True),
        ),
        migrations.AddField(
            model_name='cardtrap',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL pública de la imagen (Cloudinary, CDN, etc). Se usa con prioridad.', null=True),
        ),
        migrations.AlterField(
            model_name='cardcharacter',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy: no usar en producción sin disco persistente.', null=True, upload_to='cards/characters/'),
        ),
        migrations.AlterField(
            model_name='cardtrap',
            name='image',
            field=models.ImageField(blank=True, help_text='Legacy: no usar en producción sin disco persistente.', null=True, upload_to='cards/traps/'),
        ),
    ]
